def version = 'experiment'
@NonCPS
String transform_ssh_to_https(String url)
{
  // Rewrite SSH URLs to HTTP URLs, assuming that we don't need authentication
  def m = url =~ /^ssh:\/\/(?:\w+@)?(\w+(?:\.\w+)*\.?)(?::\d+)?\/(.+)$/
  if (!m) {
    m = url =~ /^(?:\w+@)?(\w+(?:\.\w+)*\.?):(.+)$/
  }
  m.each { match ->
    url = "https://${match[1]}/scm/${match[2]}"
  }
  return url
}
def repo = transform_ssh_to_https(scm.userRemoteConfigs[0].url.split('/')[0..-2].join('/') + '/hopic.git')

library(
    identifier: "cidriver@${version}",
    retriever: modernSCM([
        $class: 'GitSCMSource',
        remote: repo
  ]))
def cidriver = getCiDriver("git+${repo}@${version}")

pipeline {
  // Build agents/nodes get allocated when required, not before.
  agent none

  parameters {
    // Customizable by the administrator
    booleanParam(defaultValue: false,
                 description: 'Clean build',
                 name: 'CLEAN')
  }

  options {
    // Customizable by the administrator
    timestamps()
    disableConcurrentBuilds()
  }

  stages {
    stage("Commit Stage") {
      steps {
        script {
          cidriver.build(params.CLEAN)
        }
      }
    }
  }
}
